Z1 = complex(4, 3)  
Z2 = complex(6, -2)  
print(f"Z1: {Z1}")
print(f"Z2: {Z2}")
Z_eq = 1 / (1 / Z1 + 1 / Z2)
print(f"Real part of Z_eq: {Z_eq.real}")
print(f"Imaginary part of Z_eq: {Z_eq.imag}")